### ISSUE TITLE
OrderBy(string property)

### ISSUE THREAD

**Issue by dovahkiin98** [step-up-labs/firebase-database-dotnet#105]
calling that method throws a

System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at FirebaseApp.Program.Main(String[] args) in D:\Visual Studio\Projects\FirebaseApp\FirebaseApp\Program.cs:line 20

Inner Exception 1:
FirebaseException: Exception occured while processing the request.
Url: https://(link)/Devices Data/.json?orderBy="Date"
Request Data: 
Response: {
  "error" : "Index not defined, add \".indexOn\": \"Date\", for path \"/Devices Data\", to the rules"
}

Inner Exception 2:
HttpRequestException: Response status code does not indicate success: 400 (Bad Request).

**Comment by bezysoftware** [comment]
If you read the error, it will tell you what's wrong - 'Index not defined, add ".indexOn": "Date", for path "/Devices Data", to the rules'
See the official docs https://firebase.google.com/docs/database/security/indexing-data
