### ISSUE TITLE
Save and Restore Lists not working!

### ISSUE THREAD

**Issue by c-q-f** [step-up-labs/firebase-database-dotnet#224]
Hi there!

// I can save a list do database:
async static void Save()
        {
            var myColl = new List<Person>();
            myColl.Add(new Person { ID = 1, Name = "Peter" });
            myColl.Add(new Person { ID = 2, Name = "Paul" });
            myColl.Add(new Person { ID = 3, Name = "Mary" });

            FirebaseClient firebase = new FirebaseClient("https://xxxxxxxxxxxx.firebaseio.com/");
            await firebase.Child("MyApp").Child("Clients").PutAsync<List<Person>>(myColl);
        }

// but I can't restore it (an exception rises):
async static void Restore()
        {
            FirebaseClient firebase = new FirebaseClient("https://xxxxxxxxxxxx.firebaseio.com/");
            var myColl = await firebase.Child("MyApp").Child("Clients").OnceAsync<List<Person>>();
        } 

EXCEPTION:
Firebase.Database.FirebaseException
  HResult=0x80131500
  Message=Exception occured while processing the request.
Url: https://xxxxxxxxxxxxxxxx.firebaseio.com/MyApp/Clients/.json
Request Data: 
Response: [{"ID":1,"Name":"Peter"},{"ID":2,"Name":"Paul"},{"ID":3,"Name":"Mary"}]
  Source=Firebase
  StackTrace:
   at Firebase.Database.Http.HttpClientExtensions.<GetObjectCollectionAsync>d__0`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Firebase.Database.Query.FirebaseQuery.<OnceAsync>d__7`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp1.Program.<Restore>d__2.MoveNext() in D:\XM\Samples\Firebase\ConsoleApp1\ConsoleApp1\Program.cs:line 37
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  This exception was originally thrown at this call stack:
	Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(Newtonsoft.Json.JsonReader, System.Type, Newtonsoft.Json.Serialization.JsonContract)
	Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(Newtonsoft.Json.JsonReader, System.Type, Newtonsoft.Json.Serialization.JsonContract, Newtonsoft.Json.Serialization.JsonProperty, object, string)
	Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(Newtonsoft.Json.JsonReader, System.Type, bool)
	Newtonsoft.Json.JsonSerializer.DeserializeInternal(Newtonsoft.Json.JsonReader, System.Type)
	Newtonsoft.Json.JsonSerializer.Deserialize(Newtonsoft.Json.JsonReader, System.Type)
	Newtonsoft.Json.JsonConvert.DeserializeObject(string, System.Type, Newtonsoft.Json.JsonSerializerSettings)
	Newtonsoft.Json.JsonConvert.DeserializeObject<T>(string, Newtonsoft.Json.JsonSerializerSettings)
	Firebase.Database.Http.HttpClientExtensions.GetObjectCollectionAsync<T>(System.Net.Http.HttpClient, string, Newtonsoft.Json.JsonSerializerSettings)

Inner Exception 1:
JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.List`1[ConsoleApp1.Person]]' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.

**Comment by bezysoftware** [comment]
If you want to be using arrays instead of standard dictionaries, try `OnceSingleAsync`
