### ISSUE TITLE
Error when subscribed to IObservable

### ISSUE THREAD

**Issue by M1ENG** [step-up-labs/firebase-database-dotnet#29]
Hello,

I'm trying to listen to Firebase event with the following code:

```
var child = firebase.Child("Devices").Child("Status");
var observable = child.AsObservable<string>();
var subscription = observable.Where(f => f.Key == "Muted").Subscribe(d => test(d.Object));
```

It's pulling the right value from the database when it's first called. But later when the value is updated, it will throw the following exception:

For example if the value is '000f'
```
Exception thrown: 'System.FormatException' in mscorlib.ni.dll
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in Newtonsoft.Json.dll
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in Newtonsoft.Json.dll
************************************************************
Newtonsoft.Json.JsonReaderException: Input string '000f' is not a valid number. Path '', line 1, position 4. ---> System.FormatException: Additional non-parsable characters are at the end of the string.
   at System.ParseNumbers.StringToLong(String s, Int32 radix, Int32 flags, Int32* currPos)
   at System.Convert.ToInt64(String value, Int32 fromBase)
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type)
   at Firebase.Database.Streaming.FirebaseCache`1.<PushData>d__3.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Firebase.Database.Streaming.FirebaseSubscription`1.ProcessServerData(FirebaseServerEventType serverEvent, String serverData)
   at Firebase.Database.Streaming.FirebaseSubscription`1.<ReceiveThread>d__8.MoveNext()
************************************************************
Exception thrown: 'System.ArgumentException' in mscorlib.ni.dll
************************************************************
System.ArgumentException: An item with the same key has already been added. Key: Muted
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.System.Collections.IDictionary.Add(Object key, Object value)
   at Firebase.Database.Streaming.FirebaseCache`1.<PushData>d__3.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Firebase.Database.Streaming.FirebaseSubscription`1.ProcessServerData(FirebaseServerEventType serverEvent, String serverData)
   at Firebase.Database.Streaming.FirebaseSubscription`1.<ReceiveThread>d__8.MoveNext()
************************************************************
```

And if the value is 'true':

```
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in Newtonsoft.Json.dll
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in Newtonsoft.Json.dll
************************************************************
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: T. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type)
   at Firebase.Database.Streaming.FirebaseCache`1.<PushData>d__3.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Firebase.Database.Streaming.FirebaseSubscription`1.ProcessServerData(FirebaseServerEventType serverEvent, String serverData)
   at Firebase.Database.Streaming.FirebaseSubscription`1.<ReceiveThread>d__8.MoveNext()
************************************************************

```

However if the value is a number then there is no problem.

**Comment by bezysoftware** [comment]
Can you send what the data json looks like in firebase?

**Comment by M1ENG** [comment]
```
    "Devices" : {
      "Name" : "Microphone",
      "Status" : {
        "Muted" : 1,
        "Volume" : 100
      },
      "Type" : "microphone"
    },
```

Is it possible that the NuGet package I got is not up to date? The version is v1.1.5.

**Comment by bezysoftware** [comment]
It is possible, I just release v2.0.1, try using that.
