### ISSUE TITLE
i'm get  Error processing method when i'm install the lib

### ISSUE THREAD

**Issue by MichaelRodrigueess0s1** [step-up-labs/firebase-database-dotnet#298]
hello guys, I have a xamarin forms project but when I install the package and compile the solution the following problem appears, can anyone help me?

`Severity	Code	Description	Project	File	Line	Suppression State
Error		Mono.Linker.MarkException: Error processing method: 'System.Void Firebase.Database.Offline.ConcurrentOfflineDatabase::.ctor(System.Type,System.String)' in assembly: 'Firebase.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void LiteDB.LiteDatabase::.ctor(System.String,LiteDB.BsonMapper,LiteDB.Logger)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17	Evjus.Mobile.MonitoredApp.Android			
`

**Comment by gorbat-o** [comment]
Hey, same here! I updated the library to `4.1.0` from `4.0.7`. Since then, I have had the same error.
