### ISSUE TITLE
Modifying data in Firebase Console breaks Subscription

### ISSUE THREAD

**Issue by alewcock** [step-up-labs/firebase-database-dotnet#8]
Hello,

I have been testing the ConsoleChat sample, and discovered that when you manually modify a message in the Firebase Console (like changing the value of "Content"), no further notifications occur on the observable. 

The following exception is being thrown:

************************************************************
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.System.Collections.IDictionary.Add(Object key, Object value)
   at Firebase.Database.Streaming.FirebaseCache`1.<PushData>d__3.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Firebase.Database.Streaming.FirebaseSubscription`1.ProcessServerData(FirebaseServerEventType serverEvent, String serverData)
   at Firebase.Database.Streaming.FirebaseSubscription`1.<ReceiveThread>d__9.MoveNext()
************************************************************

Thanks!

**Comment by bezysoftware** [comment]
I wasn't able to reproduce your exception directly but I did notice there is bug deserializing string values (json requires them with double quotes, but firebase sends strings without them). 2c4e673844a847571ebd1ad0b8d6adceac3ec7fe Should resolve this, can you check if it also fixes your issue? 
(btw if you change just Content you will not see any output on the console as there is filtering to take out messages from you - try changing the Author instead)

**Comment by alewcock** [comment]
The problem only seems to be happening in the published version on nuget (1.1.5). When I build from the latest source, it works. So that might be another unrelated bug with the string values. 

Either way, it's all good.

Great library by the way, and thank you for making it available. I will try to contribute if I can.

Cheers!
